### PR TITLE
es and es_mx translations

### PR DESCRIPTION
**Pull request by germanvaleroelizondo**

### CODE REVIEW

**Comment by fnoks** [comment]
Hi,

Thanks for all your translation contributions ! :+1: 

Two things:
1. For this pull request, you have put the Mexican Spanish file in a subdirectory. Could you move it up?
2. The file should be named "es-mx.json" (not es_mx.json). I have fixed that for the other pull requests.

**Comment by germanvaleroelizondo** [comment]
Hi,
Sorry about # 2.
I will try to do # 1 now.

I had some difficulties, but I finally did it.

I am not a programmer, I am a veterinary pathologist contributing as translator for Moodle and Moodle-related code.

Thanks.

**Comment by germanvaleroelizondo** [comment]
Oops.

I goofed again.

Sorry about that.

**Comment by fnoks** [comment]
Thank you so much. Getting a good Spanish translation coverage will be appreciated by many out there :)

**Comment by germanvaleroelizondo** [comment]
Thanks for your understanding and patience.

Currently Spanish Moodle users are second only to English Moodle users and H5P is one of the most popular additions for Moodle. 

I would like to achieve a 90%+ Spanish translation coverage for all H5P modules while I am at home isolation because of COVID19.

**Comment by fnoks** [comment]
I am totally aware the current process for translating is far too technical, and I hope we can improve that in the future. 
Bottom line: we are very thankful for everyone who are spending their time translating! And it's no stress if there are some mistakes. It's only those who do nothing that makes no mistakes :)

**Pull request merged**
